/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        gaama: {
          primary: '#c8d643',
          secondary: '#579a4f',
          tertiary: '#9cbf48',
          accent: '#78ab4b',
          light: '#afcb48',
          dark: '#67a24d',
          green: '#89b54a',
        },
        primary: '#579a4f',
        'primary-container': '#43823d',
        'on-primary': '#ffffff',
        'on-primary-container': '#f8fff0',
        'on-primary-fixed': '#002202',
        'on-primary-fixed-variant': '#115213',
        'primary-fixed': '#c8d643',
        'primary-fixed-dim': '#93d788',
        secondary: '#546500',
        'secondary-container': '#d1ec65',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#586a00',
        'secondary-fixed': '#d3ee68',
        'secondary-fixed-dim': '#b8d24f',
        'on-secondary-fixed': '#181e00',
        'on-secondary-fixed-variant': '#3f4c00',
        tertiary: '#4a579b',
        'tertiary-container': '#6370b6',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#001257',
        'tertiary-fixed': '#dee1ff',
        'tertiary-fixed-dim': '#b9c3ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#fbf9f8',
        'on-background': '#1b1c1c',
        surface: '#fbf9f8',
        'surface-bright': '#fbf9f8',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e2',
        'surface-container-low': '#f5f3f3',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dbd9d9',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#41493e',
        'surface-tint': '#2d6b29',
        'surface-variant': '#e4e2e2',
        outline: '#717a6c',
        'outline-variant': '#c0c9ba',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f2f0f0',
        'inverse-primary': '#93d788',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      boxShadow: {
        editorial: '0px 12px 32px rgba(27, 28, 28, 0.06)',
      },
    },
  },
  plugins: [],
}
